services:
  db:
    build:
      context: ./db
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
      dockerfile: Dockerfile
    container_name: mis-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5432:5432"
    restart: always
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mis-web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/certificate_m.crt:/etc/nginx/certs/certificate_m.crt
      - ./nginx/certs/private.key:/etc/nginx/certs/private.key
    depends_on:
      - api
  api:
    build:
      context: ./server
      args:
        APP_NAME: ${APP_NAME}
        APP_VERSION: ${APP_VERSION}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        EMAIL_HOST: ${EMAIL_HOST}
        EMAIL_PORT: ${EMAIL_PORT}
        EMAIL_USER: ${EMAIL_USER}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      dockerfile: Dockerfile
    container_name: mis-api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: mis-pgadmin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    depends_on:
      - db
