services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mis-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5432:5432"
    env_file:
      - "./db.env"
    restart: always
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mis-web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/certificate_m.crt:/etc/nginx/certs/certificate_m.crt
      - ./nginx/certs/private.key:/etc/nginx/certs/private.key
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mis-api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: mis-pgadmin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5050:80"
    env_file:
      - "./pgadmin.env"
    restart: always
    depends_on:
      - db
