CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "created_at" timestamp
);

CREATE TABLE "entry_types" (
  "id" integer PRIMARY KEY,
  "name" varchar,
  "created_at" timestamp
);

CREATE TABLE "entries" (
  "id" integer PRIMARY KEY,
  "entry_id" int,
  "type_id" int,
  "release_version" varchar,
  "priority" int,
  "created_at" timestamp
);

CREATE TABLE "comments" (
  "id" integer PRIMARY KEY,
  "entry_id" int,
  "user_id" int,
  "content" text,
  "created_at" timestamp
);

ALTER TABLE "entries" ADD FOREIGN KEY ("entry_id") REFERENCES "entry_types" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
 