CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL,
  "full_name" varchar DEFAULT '',
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

CREATE TABLE "todos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" int NOT NULL,
  "task" text DEFAULT '',
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

CREATE TABLE "todo_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "todo_id" int NOT NULL,
  "status" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

ALTER TABLE "todos" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "todo_status" ADD FOREIGN KEY ("todo_id") REFERENCES "todos" ("id");