CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL,
  "full_name" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

CREATE TABLE "entry_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

CREATE TABLE "entries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "entry_type_id" int NOT NULL,
  "release_version" varchar NOT NULL,
  "priority" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "entry_id" int NOT NULL,
  "user_id" int NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id")
);

ALTER TABLE "entries" ADD FOREIGN KEY ("entry_type_id") REFERENCES "entry_types" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
