services:
  db:
    image: postgres:13.16-alpine
    container_name: server-db-mis
    restart: always
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data:
