CREATE TABLE "color_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "colors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "category_id" INT NOT NULL,
  "color_name" varchar NOT NULL,
  "hex_code" varchar NOT NULL,
  "rgb_code" varchar NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("category_id") REFERENCES "color_categories" ("id")
);

