CREATE TABLE "tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" int NOT NULL,
  "token" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "expired_at" timestamp NOT NULL,
  "is_alive" boolean NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;