CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "color_id" INT NOT NULL,
  "name" varchar NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "tags" ADD FOREIGN KEY ("color_id") REFERENCES "colors" ("id");