CREATE TABLE "member_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar NOT NULL,
  "abbr" varchar NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "member_role_id" INT NOT NULL,
  "name" varchar NOT NULL,
  "is_alive" boolean NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("id"),
  FOREIGN KEY ("member_role_id") REFERENCES "member_roles" ("id")
);

