CREATE TABLE "documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  "category_id" int NOT NULL,
  "subcategory_id" int NOT NULL,
  "post_member_id" int NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "documents" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "documents" ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "document_comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "document_id" int NOT NULL,
  "post_member_id" int NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "document_comments" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "document_relation_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "document_id" int NOT NULL,
  "member_id" int NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "document_relation_members" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "document_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "document_id" int NOT NULL,
  "tag_id" int NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "document_tags" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "user_documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" int NOT NULL,
  "document_id" int NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "user_documents" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
