CREATE TABLE "user_reset_passwords" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT NOT NULL,
  "token" varchar NOT NULL,
  "expired_at" timestamp NOT NULL,
  "is_valid" BOOLEAN NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "user_reset_passwords" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;