CREATE TABLE "color_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "colors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "category_id" INT NOT NULL,
  "name" varchar NOT NULL,
  "hex_code" varchar NOT NULL,
  "rgb_code" varchar NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("category_id") REFERENCES "color_categories" ("id")
);

CREATE TABLE "user_color_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT NOT NULL,
  "color_category_id" INT NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "user_color_categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_color_categories" ADD FOREIGN KEY ("color_category_id") REFERENCES "color_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;