CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "is_alive" boolean NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "subcategories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "category_id" int NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "is_alive" boolean NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "subcategories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX "idx_subcategories_category_id" ON "subcategories" ("id", "category_id");

CREATE TABLE "user_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT NOT NULL,
  "category_id" INT NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "user_categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;