CREATE TABLE "user_registers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT NOT NULL,
  "token" varchar NOT NULL,
  "expired_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "user_registers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "users" ADD COLUMN "is_registered" BOOLEAN NOT NULL DEFAULT FALSE;