CREATE TABLE "document_updated_histories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "document_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "document_updated_histories" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
